### ISSUE TITLE
Build issues with out of sync depencencies

### ISSUE THREAD

**Issue by panzerdev** [caddy-dns/lego-deprecated#1]
What did I do:

`xcaddy build --with github.com/caddy-dns/lego-deprecated`

```
2020/08/11 20:00:03 [INFO] Temporary folder: /tmp/buildenv_2020-08-11-2000.315748876
2020/08/11 20:00:03 [INFO] Writing main module: /tmp/buildenv_2020-08-11-2000.315748876/main.go
2020/08/11 20:00:03 [INFO] Initializing Go module
2020/08/11 20:00:03 [INFO] exec (timeout=10s): /usr/local/go/bin/go mod init caddy 
go: creating new go.mod: module caddy
2020/08/11 20:00:03 [INFO] Pinning versions
2020/08/11 20:00:03 [INFO] exec (timeout=0s): /usr/local/go/bin/go get -d -v github.com/caddyserver/caddy/v2 
go: github.com/caddyserver/caddy/v2 upgrade => v2.1.1
2020/08/11 20:00:04 [INFO] exec (timeout=0s): /usr/local/go/bin/go get -d -v github.com/caddy-dns/lego-deprecated 
go: github.com/caddy-dns/lego-deprecated upgrade => v0.0.0-20200730210111-828437887330
go: downloading github.com/mholt/acmez v0.1.0
go: downloading github.com/aws/aws-sdk-go v1.30.20
2020/08/11 20:00:10 [INFO] Build environment ready
2020/08/11 20:00:10 [INFO] Building Caddy
2020/08/11 20:00:10 [INFO] exec (timeout=0s): /usr/local/go/bin/go build -o /home/mpa/abiliware/caddy/caddy -ldflags -w -s -trimpath 
2020/08/11 20:00:15 [INFO] Build complete: caddy
2020/08/11 20:00:15 [INFO] Cleaning up temporary folder: /tmp/buildenv_2020-08-11-2000.315748876
```

worked and built.

Then I check with this config
```
{
	"storage": {
		"module": "file_system",
		"root": "/app/certs"
	}	,
	"apps": {
		"tls": {
			"automation": {
				"policies":[ {
					"issuer": {
						"module": "acme",
						"ca": "https://acme-staging-v02.api.letsencrypt.org/directory",
						"test_ca": "https://acme-staging-v02.api.letsencrypt.org/directory",
						"email": "support@some.thing",
						"challenges": {
							"dns": {
								"provider": {
									"name": "lego_deprecated",
									"provider_name": "autodns"
								}
							}
						}
					}
				}
				]
			}
		}		,
		"http": {
			"servers": {
				"srv0": {
					"listen": [":443"],
					"automatic_https": {},
					"routes": [ {
						"match": [ {
							"host": ["some.thing.com"]
						}
						],
						"handle": [ {
							"handler":"subroute",
							"routes": [ {
								"handle": [ {
									"handler":"reverse_proxy",
									"upstreams": [ {
										"dial": "localhost:8081"
									}
									]
								}
								]
							}
							]
						}
						]
					}
					]
				}
			}
		}
	}
}
```

Validating with this command `AUTODNS_API_USER=2 AUTODNS_API_PASSWORD=3 ./caddy validate -config caddy.json`

```
2020/08/11 18:03:34.971	INFO	using provided configuration	{"config_file": "caddy.json", "config_adapter": ""}
2020/08/11 20:03:34 [INFO][cache:0xc00051ce40] Started certificate maintenance routine
panic: interface conversion: *legodeprecated.LegoDeprecated is not caddytls.recordManager: missing method AppendRecords

goroutine 1 [running]:
github.com/caddyserver/caddy/v2/modules/caddytls.(*ACMEIssuer).Provision(0xc0009a6120, 0x27bec20, 0xc0005c10c0, 0xc000994d50, 0xc0007e12c0, 0x0, 0x0, 0x0, 0x11, 0x11)
	github.com/caddyserver/caddy/v2@v2.1.1/modules/caddytls/acmeissuer.go:104 +0x654
github.com/caddyserver/caddy/v2.Context.LoadModuleByID(0x27bec20, 0xc0005c10c0, 0xc000994d50, 0xc0007e12c0, 0x0, 0x0, 0x0, 0xc000051700, 0x11, 0xc0002f7500, ...)
	github.com/caddyserver/caddy/v2@v2.1.1/context.go:344 +0x66a
github.com/caddyserver/caddy/v2.Context.loadModuleInline(0x27bec20, 0xc0005c10c0, 0xc000994d50, 0xc0007e12c0, 0x0, 0x0, 0x0, 0x1e3ff11, 0x6, 0x1e3fef9, ...)
	github.com/caddyserver/caddy/v2@v2.1.1/context.go:394 +0x177
github.com/caddyserver/caddy/v2.Context.LoadModule(0x27bec20, 0xc0005c10c0, 0xc000994d50, 0xc0007e12c0, 0x0, 0x0, 0x0, 0x1e45640, 0xc00098efa0, 0x2238ad4, ...)
	github.com/caddyserver/caddy/v2@v2.1.1/context.go:161 +0x4df
github.com/caddyserver/caddy/v2/modules/caddytls.(*AutomationPolicy).Provision(0xc00098efa0, 0xc00098c4d0, 0x0, 0x0)
	github.com/caddyserver/caddy/v2@v2.1.1/modules/caddytls/automation.go:177 +0x649
github.com/caddyserver/caddy/v2/modules/caddytls.(*TLS).Provision(0xc00098c4d0, 0x27bec20, 0xc0005c10c0, 0xc000994d50, 0xc0007e12c0, 0x0, 0x0, 0x0, 0xc000419af0, 0x0)
	github.com/caddyserver/caddy/v2@v2.1.1/modules/caddytls/tls.go:145 +0x602
github.com/caddyserver/caddy/v2.Context.LoadModuleByID(0x27bec20, 0xc0005c10c0, 0xc000994d50, 0xc0007e12c0, 0x0, 0x0, 0x0, 0xc00031afdc, 0x3, 0xc0009a2000, ...)
	github.com/caddyserver/caddy/v2@v2.1.1/context.go:344 +0x66a
github.com/caddyserver/caddy/v2.Context.App(0x27bec20, 0xc0005c10c0, 0xc000994d50, 0xc0007e12c0, 0x0, 0x0, 0x0, 0xc00031afdc, 0x3, 0x27d5de0, ...)
	github.com/caddyserver/caddy/v2@v2.1.1/context.go:415 +0x165
github.com/caddyserver/caddy/v2.run.func3(0xc0007e12c0, 0x27bec20, 0xc0005c10c0, 0xc000994d50, 0xc0007e12c0, 0x0, 0x0, 0x0, 0x0, 0x0)
	github.com/caddyserver/caddy/v2@v2.1.1/caddy.go:388 +0xdc
github.com/caddyserver/caddy/v2.run(0xc0007e12c0, 0xc00000e500, 0x0, 0x0)
	github.com/caddyserver/caddy/v2@v2.1.1/caddy.go:393 +0x27a
github.com/caddyserver/caddy/v2.Validate(0xc0007e12c0, 0x40f, 0x480)
	github.com/caddyserver/caddy/v2@v2.1.1/caddy.go:482 +0x30
github.com/caddyserver/caddy/v2/cmd.cmdValidateConfig(0xc00011c4e0, 0xc00004c0e0, 0x2, 0x2)
	github.com/caddyserver/caddy/v2@v2.1.1/cmd/commandfuncs.go:521 +0x26d
github.com/caddyserver/caddy/v2/cmd.Main()
	github.com/caddyserver/caddy/v2@v2.1.1/cmd/main.go:85 +0x239
main.main()
	caddy/main.go:12 +0x20
```

2. So I tried `master` `xcaddy build master --with github.com/caddy-dns/lego-deprecated`

```
2020/08/11 20:04:44 [INFO] Temporary folder: /tmp/buildenv_2020-08-11-2004.484134970
2020/08/11 20:04:44 [INFO] Writing main module: /tmp/buildenv_2020-08-11-2004.484134970/main.go
2020/08/11 20:04:44 [INFO] Initializing Go module
2020/08/11 20:04:44 [INFO] exec (timeout=10s): /usr/local/go/bin/go mod init caddy 
go: creating new go.mod: module caddy
2020/08/11 20:04:44 [INFO] Pinning versions
2020/08/11 20:04:44 [INFO] exec (timeout=0s): /usr/local/go/bin/go get -d -v github.com/caddyserver/caddy/v2@master 
go: downloading github.com/caddyserver/caddy v1.0.6-0.20200303163406-891446d06340
go: downloading github.com/caddyserver/caddy/v2 v2.2.0-rc.1.0.20200811172619-e385be922569
go: github.com/caddyserver/caddy/v2 master => v2.2.0-rc.1.0.20200811172619-e385be922569
2020/08/11 20:04:58 [INFO] exec (timeout=0s): /usr/local/go/bin/go get -d -v github.com/caddy-dns/lego-deprecated 
go: github.com/caddy-dns/lego-deprecated upgrade => v0.0.0-20200730210111-828437887330
2020/08/11 20:04:59 [INFO] Build environment ready
2020/08/11 20:04:59 [INFO] Building Caddy
2020/08/11 20:04:59 [INFO] exec (timeout=0s): /usr/local/go/bin/go build -o /home/mpa/abiliware/caddy/caddy -ldflags -w -s -trimpath 
# github.com/smallstep/certificates/authority/provisioner
/home/mpa/go/pkg/mod/github.com/smallstep/certificates@v0.15.0-rc.1.0.20200506212953-e855707dc274/authority/provisioner/jwk.go:155:24: assignment mismatch: 3 variables but x509util.SplitSANs returns 4 values
/home/mpa/go/pkg/mod/github.com/smallstep/certificates@v0.15.0-rc.1.0.20200506212953-e855707dc274/authority/provisioner/x5c.go:197:24: assignment mismatch: 3 variables but x509util.SplitSANs returns 4 values
2020/08/11 20:05:00 [INFO] Cleaning up temporary folder: /tmp/buildenv_2020-08-11-2004.484134970
2020/08/11 20:05:00 [FATAL] exit status 2
``` 

It worked when I checked out `lego-deprecated` and updated `go get -u github.com/caddyserver/caddy/v2@v2.2.0-rc.1` and build with `xcaddy build master --with github.com/caddy-dns/lego-deprecated=../lego-deprecated`

**Comment by mholt** [comment]
Yeah, so unfortunately (or actually, that's probably "fortunately") the `go` tool won't use pre-release tags by default. If you want to use a pre-release, you'll have to specify that in your command (as you discovered).

As of now, this command works: `xcaddy build v2.2.0-rc.1 --with github.com/caddy-dns/lego-deprecated`

Things should smooth out again after 2.2 is no longer a pre-release.

**Comment by panzerdev** [comment]
So is there the need to always keep plugins up to date with caddy in the `go.mod` file in general?

**Comment by mholt** [comment]
No, just this one time we transitioned to [our new ACME library](https://github.com/mholt/acmez) which bubbled up through several dependencies. I don't think plugins _always_ have to point to the latest version of Caddy in general.

Closing then? Feel free to reopen if something is definitely still broken.
